name: pkgcheck
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pkgcore/pkgcheck-action@v1
        with:
          args: --net
